import type { AttendanceEntry, GuardianLink, PlatformWorkspace, SchoolDocument, StudentRecord, TimetableSlot } from "./types";

export type TimetableConflict={slotId:string;otherSlotId:string;reason:"teacher"|"class"|"room"};
const minutes=(value:string)=>{const[hours,mins]=value.split(":").map(Number);return hours*60+mins;};

export function timetableSlotsOverlap(a:TimetableSlot,b:TimetableSlot){return a.weekday===b.weekday&&minutes(a.startsAt)<minutes(b.endsAt)&&minutes(b.startsAt)<minutes(a.endsAt);}
export function detectTimetableConflicts(slots:TimetableSlot[]){const conflicts:TimetableConflict[]=[];for(let i=0;i<slots.length;i+=1){for(let j=i+1;j<slots.length;j+=1){const a=slots[i],b=slots[j];if(!timetableSlotsOverlap(a,b))continue;if(a.teacherId&&a.teacherId===b.teacherId)conflicts.push({slotId:a.id,otherSlotId:b.id,reason:"teacher"});if(a.classId&&a.classId===b.classId)conflicts.push({slotId:a.id,otherSlotId:b.id,reason:"class"});if(a.room&&a.room===b.room)conflicts.push({slotId:a.id,otherSlotId:b.id,reason:"room"});}}return conflicts;}

export function calculateAttendance(entries:AttendanceEntry[],expectedMinutes?:number){const absences=entries.filter(item=>item.kind==="absence");const unjustified=absences.filter(item=>!item.justified).length;const lateCount=entries.filter(item=>item.kind==="late").length;const earlyLeaves=entries.filter(item=>item.kind==="early_leave").length;const missedMinutes=entries.reduce((sum,item)=>sum+Math.max(0,item.durationMinutes),0);return{absenceCount:absences.length,unjustifiedAbsenceCount:unjustified,lateCount,earlyLeaveCount:earlyLeaves,missedMinutes,attendanceRate:expectedMinutes&&expectedMinutes>0?Math.max(0,Math.round((1-missedMinutes/expectedMinutes)*10000)/100):null,rateIsExact:Boolean(expectedMinutes&&expectedMinutes>0)};}

export function guardianCanAccessStudent(guardianId:string,studentId:string,links:GuardianLink[]){return links.some(item=>item.guardianId===guardianId&&item.studentId===studentId);}

export function transferStudent(students:StudentRecord[],studentId:string,targetClassId:string,targetAcademicYearId:string){const target=students.find(item=>item.id===studentId);if(!target)throw new Error("Élève introuvable.");if(!targetClassId||!targetAcademicYearId)throw new Error("La classe et l’année de destination sont obligatoires.");return students.map(item=>item.id===studentId?{...item,classId:targetClassId,academicYearId:targetAcademicYearId,status:"active" as const,updatedAt:new Date().toISOString()}:item);}

export function platformStatistics(workspace:PlatformWorkspace,classIds?:readonly string[]){const officialClassIds=classIds?new Set(classIds.filter(Boolean)):new Set(workspace.students.map(item=>item.classId).filter(Boolean));const classesWithHeadTeacher=new Set(workspace.assignments.filter(item=>item.headTeacher&&item.active).map(item=>item.classId));return{studentCount:workspace.students.filter(item=>item.status==="active").length,teacherCount:workspace.users.filter(item=>["teacher","head_teacher"].includes(item.role)&&item.status==="active").length,classCount:officialClassIds.size,todayAbsences:workspace.attendance.filter(item=>item.kind==="absence"&&item.date===new Date().toISOString().slice(0,10)).length,pendingInvitations:workspace.users.filter(item=>item.invitationStatus==="pending").length,activePeriods:workspace.periods.filter(item=>item.active&&!item.locked).length,unassignedSubjects:workspace.subjects.filter(subject=>subject.active&&!workspace.assignments.some(item=>item.subjectId===subject.id&&item.active)).length,classesWithoutHeadTeacher:[...officialClassIds].filter(classId=>!classesWithHeadTeacher.has(classId)).length,conflictCount:detectTimetableConflicts(workspace.timetable).length,publishedAnnouncements:workspace.announcements.filter(item=>item.status==="published").length};}

export function createDocumentModel(input:{kind:SchoolDocument["kind"];schoolName:string;studentName?:string;className?:string;academicYear?:string;issuedAt:string}){const titles:Record<SchoolDocument["kind"],string>={enrollment_certificate:"Certificat de scolarité",registration_attestation:"Attestation d’inscription",student_record:"Fiche élève",class_list:"Liste de classe",teacher_list:"Liste des enseignants",transcript:"Relevé de notes",report_card:"Bulletin scolaire",timetable:"Emploi du temps",attendance_sheet:"Feuille de présence",student_card:"Carte scolaire",summons:"Convocation"};return{title:titles[input.kind],schoolName:input.schoolName||"Enseignant individuel",studentName:input.studentName||"",className:input.className||"",academicYear:input.academicYear||"",issuedAt:input.issuedAt,disclaimer:"Modèle configurable — à adapter aux exigences de l’établissement et aux textes officiels applicables."};}

export function periodCanBeLocked(args:{missingScores:number;invalidCoefficients:number;role:string}){if(args.missingScores>0)return{allowed:false,reason:"Des notes sont encore manquantes."};if(args.invalidCoefficients>0)return{allowed:false,reason:"Des coefficients sont invalides."};if(!["school_admin","headmaster","super_admin"].includes(args.role))return{allowed:false,reason:"Ce rôle ne peut pas verrouiller la période."};return{allowed:true,reason:"Période prête à être verrouillée."};}

export function canTransitionReport(from:string,to:string,role:string){const transitions:Record<string,string[]>={draft:["calculated"],calculated:["review"],review:["validated"],validated:["locked"],locked:["published","review"],published:["review"]};if(!transitions[from]?.includes(to))return false;if(["validated","locked","published"].includes(to))return["school_admin","headmaster","super_admin"].includes(role);if(from==="locked"&&to==="review")return["school_admin","headmaster","super_admin"].includes(role);return["teacher","head_teacher","academic_director","school_admin","headmaster","super_admin"].includes(role);}
