"use client";

import { readClasses } from "@/lib/class-store";
import { STORAGE_KEYS,readLocal } from "@/lib/storage-mode";
import type { MigrationJournalEntry,PlatformWorkspace,StudentRecord } from "./types";

export function detectV07Data(){const classes=readClasses();const evaluations=readLocal<unknown[]>(STORAGE_KEYS.evaluations,[]);const lessons=readLocal<unknown[]>(STORAGE_KEYS.lessons,[]);const grading=readLocal<Record<string,unknown>>(STORAGE_KEYS.grading,{});return{classes:classes.length,students:classes.reduce((sum,item)=>sum+item.students.length,0),evaluations:evaluations.length,lessons:lessons.length,grading:Object.keys(grading).length?1:0};}

export function migrateV07Classes(workspace:PlatformWorkspace,schoolId:string,academicYearId:string){const classes=readClasses();const existingNumbers=new Set(workspace.students.map(item=>item.registrationNumber).filter(Boolean));const existingIdentity=new Set(workspace.students.map(item=>`${item.firstName}|${item.lastName}|${item.classId}`.toLocaleLowerCase("fr")));const imported:StudentRecord[]=[];for(const group of classes){for(const student of group.students){const identity=`${student.firstName}|${student.lastName}|${group.id}`.toLocaleLowerCase("fr");if((student.registrationNumber&&existingNumbers.has(student.registrationNumber))||existingIdentity.has(identity))continue;imported.push({id:student.id,schoolId,academicYearId,classId:group.id,registrationNumber:student.registrationNumber||"",firstName:student.firstName,lastName:student.lastName,gender:"",dateOfBirth:student.dateOfBirth||"",placeOfBirth:"",nationality:"Gabonaise",photoUrl:"",address:"",phone:"",email:student.email,previousSchool:"",enrolledOn:new Date().toISOString().slice(0,10),status:"active",specialNeeds:"",emergencyContact:"",administrativeNotes:"Importé depuis Mes classes v0.7.0",limitedMedicalNotes:"",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});}}
const detected=detectV07Data();const journal:MigrationJournalEntry={id:crypto.randomUUID(),detectedAt:new Date().toISOString(),confirmedAt:new Date().toISOString(),status:"confirmed",sourceCounts:detected,importedCounts:{students:imported.length},notes:"Migration locale v0.7.0 confirmée sans doublons."};return{workspace:{...workspace,students:[...workspace.students,...imported],migrationJournal:[journal,...workspace.migrationJournal]},imported:imported.length,journal};}
