"use client";

import { useEffect, useMemo, useState } from "react";
import { Banknote, CalendarCheck, FileText, LayoutDashboard, Printer, Receipt, Search, Settings, Users } from "lucide-react";
import { AdminMegaNav } from "@/components/SpaceNavigation";
import { Brand } from "@/components/Brand";
import { canConfigureFinance } from "@/lib/finance/policy";
import { buildInstallments, formatFcfa, librevilleDate, paymentMethodBreakdown, paidTotal, requiredTotal, remainingTotal } from "@/lib/finance/calculations";
import { applyScaleCollectively, cancelPayment, closeCash, configureScale, loadFinanceData, recordPayment, resolveFinanceContext, saveFeeType, saveSettings, type FinanceContext, type PaymentRow } from "@/lib/finance/store";
import styles from "./FinanceManager.module.css";
import { ScaleConfigurator } from "./ScaleConfigurator";
import { StudentFinanceFile } from "./StudentFinanceFile";

type Loaded = Awaited<ReturnType<typeof loadFinanceData>>;
type Tab = "dashboard"|"fees"|"payment"|"students"|"families"|"cash"|"settings";
const tabs: Array<{id:Tab;label:string;icon:typeof Banknote}> = [
  {id:"dashboard",label:"Tableau de bord",icon:LayoutDashboard},{id:"fees",label:"Tarifs et échéanciers",icon:CalendarCheck},
  {id:"payment",label:"Encaissement",icon:Banknote},{id:"students",label:"Élèves et impayés",icon:Users},
  {id:"families",label:"Familles",icon:Users},{id:"cash",label:"Caisse",icon:Receipt},{id:"settings",label:"Paramètres",icon:Settings},
];

export function FinanceManager() {
  const [tab,setTab]=useState<Tab>("dashboard"); const [context,setContext]=useState<FinanceContext|null>(null);
  const [data,setData]=useState<Loaded|null>(null); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false);
  const [query,setQuery]=useState(""); const [selectedStudent,setSelectedStudent]=useState(""); const [selectedInstallment,setSelectedInstallment]=useState("");
  const [amount,setAmount]=useState(""); const [payer,setPayer]=useState(""); const [method,setMethod]=useState("cash"); const [receipt,setReceipt]=useState<PaymentRow|null>(null);

  async function reload(current=context){ if(!current)return; setError(""); try{setData(await loadFinanceData(current));}catch(e){setError(e instanceof Error?e.message:"Chargement impossible.");} }
  useEffect(()=>{void(async()=>{try{const current=await resolveFinanceContext();setContext(current);setData(await loadFinanceData(current));}catch(e){setError(e instanceof Error?e.message:"Initialisation impossible.");}})();},[]);
  const manager=canConfigureFinance(context?.role||null); const today=librevilleDate();
  const activePayments=data?.payments.filter(p=>p.status==="active")||[]; const todayPayments=activePayments.filter(p=>librevilleDate(p.paid_at)===today);
  const todayClosure=data?.closures.find(c=>c.cash_date===today&&c.cashier_id===context?.userId); const postClosureCancellations=data?.payments.filter(p=>p.status==="cancelled"&&librevilleDate(p.paid_at)===today&&p.cancelled_at&&todayClosure&&p.cancelled_at>todayClosure.closed_at)||[];
  const totalRequired=requiredTotal(data?.charges.map(c=>({amountFcfa:c.amount_fcfa}))||[]); const totalPaid=paidTotal(activePayments.map(p=>({id:p.id,amountFcfa:p.amount_fcfa,paidAt:p.paid_at,status:"active",method:p.payment_method})));
  const filteredStudents=useMemo(()=>{const needle=query.trim().toLowerCase();return (data?.students||[]).filter(s=>!needle||`${s.last_name} ${s.first_name} ${s.registration_number||""}`.toLowerCase().includes(needle));},[data,query]);
  const selectedCharges=data?.charges.filter(c=>c.student_id===selectedStudent)||[]; const installmentIds=new Set(selectedCharges.map(c=>c.id)); const selectedInstallments=data?.installments.filter(i=>installmentIds.has(i.charge_id)&&i.status==="active")||[];
  async function act(action:()=>Promise<unknown>, success:string){setBusy(true);setError("");setNotice("");try{await action();setNotice(success);await reload();}catch(e){setError(e instanceof Error?e.message:"Opération impossible.");}finally{setBusy(false);}}
  async function applyCollectively(scaleId:string){setBusy(true);setError("");setNotice("");try{const result=await applyScaleCollectively(scaleId);setNotice(`Attribution terminée : ${result.created_count} créée(s), ${result.existing_count} déjà correcte(s), ${result.overshadowed_count} couverte(s) par un barème plus précis, ${result.conflict_count} conflit(s) à examiner.`);await reload();}catch(e){setError(e instanceof Error?e.message:"Attribution collective impossible.");}finally{setBusy(false);}}
  async function collect(){if(!context||!selectedStudent||!selectedInstallment)return setError("Sélectionnez un élève et une échéance."); const value=Number(amount); setBusy(true);setError("");try{const result=await recordPayment(context,{studentId:selectedStudent,payerName:payer,amountFcfa:value,method,installmentId:selectedInstallment});setReceipt(result);setAmount("");setSelectedInstallment("");setNotice("Paiement enregistré. Le reçu est prêt à imprimer.");await reload();}catch(e){setError(e instanceof Error?e.message:"Paiement impossible.");}finally{setBusy(false);}}

  return <main className={styles.page}>
    <header className={styles.brand}><Brand/><div><b>Comptabilité et frais de scolarité</b><span>Encaissements, reçus, impayés et caisse</span></div></header><AdminMegaNav onLogout={()=>{}}/>
    <nav className={styles.tabs}>{tabs.map(item=><button key={item.id} className={tab===item.id?styles.active:""} onClick={()=>setTab(item.id)}><item.icon/>{item.label}</button>)}</nav>
    {error&&<p className={styles.error} role="alert">{error}</p>}{notice&&<p className={styles.success}>{notice}</p>}
    {!data&&!error&&<p className={styles.loading}>Chargement des données financières…</p>}
    {data&&<section className={styles.content}>
      {tab==="dashboard"&&<><div className={styles.hero}><div><small>Année scolaire active</small><h1>Pilotage financier</h1><p>Les chiffres sont issus des encaissements enregistrés, hors paiements annulés.</p></div><Banknote/></div><div className={styles.stats}>
        <article><small>Encaissé aujourd’hui</small><b>{formatFcfa(todayPayments.reduce((s,p)=>s+p.amount_fcfa,0))}</b></article><article><small>Encaissé sur la période</small><b>{formatFcfa(totalPaid)}</b></article><article><small>Montant réclamé</small><b>{formatFcfa(totalRequired)}</b></article><article><small>Reste à recouvrer</small><b>{formatFcfa(remainingTotal(totalRequired,totalPaid))}</b></article>
      </div><Operations payments={data.payments} onCancel={manager?(p)=>{const reason=prompt("Motif obligatoire de l’annulation :")||"";if(reason)void act(()=>cancelPayment(p.id,reason),"Paiement annulé et conservé dans l’historique.");}:undefined}/></>}
      {tab==="fees"&&<div className={styles.panel}><h2>Tarifs et échéanciers</h2>{manager?<><FeeForm disabled={busy} onSave={(input)=>act(()=>saveFeeType(context!,input),"Type de frais créé.")}/><ScaleConfigurator data={data} schoolId={context!.schoolId} disabled={busy} onScale={input=>act(()=>configureScale(context!,input),"Barème et échéance créés.")} onApply={scale=>void applyCollectively(scale)}/></>:<p>Le secrétariat peut consulter les frais, mais leur configuration est réservée à la direction.</p>}<table><thead><tr><th>Code</th><th>Libellé</th><th>Catégorie</th><th>État</th></tr></thead><tbody>{data.fees.map(f=><tr key={f.id}><td>{f.code}</td><td>{f.label}</td><td>{f.category}</td><td>{f.is_active?"Actif":"Inactif"}</td></tr>)}</tbody></table></div>}
      {tab==="payment"&&<div className={styles.panel}><h2>Nouvel encaissement</h2><label className={styles.search}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nom ou matricule de l’élève"/></label><div className={styles.form}><label>Élève<select value={selectedStudent} onChange={e=>{setSelectedStudent(e.target.value);setSelectedInstallment("");}}><option value="">Sélectionner</option>{filteredStudents.map(s=><option key={s.id} value={s.id}>{s.last_name} {s.first_name} — {s.registration_number||"sans matricule"}</option>)}</select></label><label>Échéance<select value={selectedInstallment} onChange={e=>{setSelectedInstallment(e.target.value);const i=selectedInstallments.find(x=>x.id===e.target.value);if(i)setAmount(String(i.amount_fcfa));}}><option value="">Sélectionner</option>{selectedInstallments.map(i=><option key={i.id} value={i.id}>{i.label} — {formatFcfa(i.amount_fcfa)} — {i.due_on}</option>)}</select></label><label>Montant FCFA<input type="number" min="1" step="1" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Nom du payeur<input value={payer} onChange={e=>setPayer(e.target.value)}/></label><label>Moyen<select value={method} onChange={e=>setMethod(e.target.value)}><option value="cash">Espèces</option><option value="airtel_money">Airtel Money</option><option value="moov_money">Moov Money</option><option value="bank_transfer">Virement</option><option value="cheque">Chèque</option><option value="other">Autre</option></select></label><button disabled={busy||!payer.trim()} onClick={()=>void collect()}>{busy?"Enregistrement…":"Confirmer l’encaissement"}</button></div>{receipt&&<ReceiptView payment={receipt} student={data.students.find(s=>s.id===receipt.student_id)}/>}</div>}
      {tab==="students"&&<div className={styles.panel}><h2>Élèves et impayés</h2><label className={styles.search}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher"/></label><table><thead><tr><th>Élève</th><th>Matricule</th><th>Exigé</th><th>Payé</th><th>Reste</th><th></th></tr></thead><tbody>{filteredStudents.map(s=>{const due=data.charges.filter(c=>c.student_id===s.id).reduce((n,c)=>n+c.amount_fcfa,0);const paid=data.payments.filter(p=>p.student_id===s.id&&p.status==="active").reduce((n,p)=>n+p.amount_fcfa,0);return <tr key={s.id}><td>{s.last_name} {s.first_name}</td><td>{s.registration_number||"—"}</td><td>{formatFcfa(due)}</td><td>{formatFcfa(paid)}</td><td>{formatFcfa(remainingTotal(due,paid))}</td><td><button onClick={()=>setSelectedStudent(s.id)}>Ouvrir la fiche</button></td></tr>})}</tbody></table>{selectedStudent&&<StudentFinanceFile student={data.students.find(s=>s.id===selectedStudent)} charges={data.charges.filter(c=>c.student_id===selectedStudent)} installments={data.installments.filter(i=>new Set(data.charges.filter(c=>c.student_id===selectedStudent).map(c=>c.id)).has(i.charge_id))} payments={data.payments.filter(p=>p.student_id===selectedStudent)}/>}</div>}
      {tab==="families"&&<div className={styles.panel}><h2>Situation des familles</h2>{data.guardians.map(g=>{const ids=data.links.filter(l=>l.guardian_id===g.id).map(l=>l.student_id);const due=data.charges.filter(c=>ids.includes(c.student_id)).reduce((s,c)=>s+c.amount_fcfa,0);const paid=data.payments.filter(p=>ids.includes(p.student_id)&&p.status==="active").reduce((s,p)=>s+p.amount_fcfa,0);return <article key={g.id}><h3>{g.last_name} {g.first_name}</h3><p>{ids.map(id=>{const child=data.students.find(s=>s.id===id);return child?`${child.last_name} ${child.first_name}`:""}).filter(Boolean).join(", ")||"Aucun enfant lié"}</p><b>{formatFcfa(due)} exigés · {formatFcfa(paid)} payés · {formatFcfa(remainingTotal(due,paid))} restants</b></article>})}<p className={styles.note}>Regroupements issus des liens parent-enfant enregistrés.</p></div>}
      {tab==="cash"&&<div className={styles.panel}><article className={styles.cashPrint}><h2>Caisse du {new Intl.DateTimeFormat("fr-FR").format(new Date())}</h2><div className={styles.stats}><article><small>Paiements</small><b>{todayClosure?.payment_count??todayPayments.length}</b></article><article><small>Total historique</small><b>{formatFcfa(todayClosure?.total_fcfa??todayPayments.reduce((s,p)=>s+p.amount_fcfa,0))}</b></article>{Object.entries(todayClosure?.method_totals??paymentMethodBreakdown(todayPayments.map(p=>({id:p.id,amountFcfa:p.amount_fcfa,paidAt:p.paid_at,status:"active",method:p.payment_method})))).map(([m,v])=><article key={m}><small>{m}</small><b>{formatFcfa(v)}</b></article>)}</div>{todayClosure&&<p>Caisse clôturée le {new Date(todayClosure.closed_at).toLocaleString("fr-FR")}.</p>}{postClosureCancellations.length>0&&<section><h3>Annulations postérieures à la clôture</h3><ul>{postClosureCancellations.map(p=><li key={p.id}>{p.receipt_number} · {formatFcfa(p.amount_fcfa)} · {new Date(p.cancelled_at!).toLocaleString("fr-FR")} · auteur {p.cancelled_by} · {p.cancellation_reason}</li>)}</ul></section>}</article><button className={styles.noPrint} onClick={()=>window.print()}><Printer/>Imprimer le récapitulatif</button> {!todayClosure&&<button disabled={busy} onClick={()=>confirm("Confirmer la clôture définitive de cette caisse ?")&&void act(()=>closeCash(context!,today),"Caisse clôturée.")}>Clôturer ma caisse</button>}</div>}
      {tab==="settings"&&<div className={styles.panel}><h2>Paramètres financiers</h2>{manager?<SettingsForm initial={data.settings} disabled={busy} onSave={(settings)=>act(()=>saveSettings(context!,settings),"Paramètres enregistrés.")}/>:<p>Ces paramètres sont réservés à la direction.</p>}</div>}
    </section>}
  </main>;
}

function FeeForm({disabled,onSave}:{disabled:boolean;onSave:(v:{code:string;label:string;category:string})=>void}){const[code,setCode]=useState("");const[label,setLabel]=useState("");const[category,setCategory]=useState("tuition");return <div className={styles.form}><label>Code<input value={code} onChange={e=>setCode(e.target.value)}/></label><label>Libellé<input value={label} onChange={e=>setLabel(e.target.value)}/></label><label>Catégorie<select value={category} onChange={e=>setCategory(e.target.value)}><option value="registration">Inscription</option><option value="tuition">Scolarité</option><option value="transport">Transport</option><option value="canteen">Cantine</option><option value="supplies">Fournitures</option><option value="activities">Activités</option><option value="other">Autres</option></select></label><button disabled={disabled||!code.trim()||!label.trim()} onClick={()=>onSave({code,label,category})}>Créer le type</button></div>}
function ScaleForm({fees,students,scales,disabled,onScale,onAssign}:{fees:Loaded["fees"];students:Loaded["students"];scales:Loaded["scales"];disabled:boolean;onScale:(v:{feeTypeId:string;amountFcfa:number;publish:boolean;mode:string;installments:ReturnType<typeof buildInstallments>})=>void;onAssign:(scale:string,student:string)=>void}){const[fee,setFee]=useState("");const[amount,setAmount]=useState("");const[due,setDue]=useState("");const[publish,setPublish]=useState(false);const[mode,setMode]=useState<"single"|"monthly"|"quarterly"|"custom">("single");const[count,setCount]=useState("1");const[scale,setScale]=useState("");const[student,setStudent]=useState("");return <><h3>Créer un barème et son échéancier</h3><div className={styles.form}><label>Type de frais<select value={fee} onChange={e=>setFee(e.target.value)}><option value="">Sélectionner</option>{fees.map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></label><label>Montant FCFA<input type="number" min="1" step="1" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Fréquence<select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="single">Paiement unique</option><option value="monthly">Mensuel</option><option value="quarterly">Trimestriel</option><option value="custom">Personnalisé régulier</option></select></label><label>Nombre d’échéances<input type="number" min="1" max="24" value={count} disabled={mode==="single"} onChange={e=>setCount(e.target.value)}/></label><label>Première échéance<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label className={styles.check}><input type="checkbox" checked={publish} onChange={e=>setPublish(e.target.checked)}/>Visible des parents</label><button disabled={disabled||!fee||!due||Number(amount)<=0} onClick={()=>onScale({feeTypeId:fee,amountFcfa:Number(amount),publish,mode,installments:buildInstallments(Number(amount),due,mode,Number(count))})}>Créer le barème</button></div><h3>Attribuer un barème à un élève</h3><div className={styles.form}><label>Barème<select value={scale} onChange={e=>setScale(e.target.value)}><option value="">Sélectionner</option>{scales.map(s=><option key={s.id} value={s.id}>{fees.find(f=>f.id===s.fee_type_id)?.label||"Frais"} — {formatFcfa(s.amount_fcfa)}</option>)}</select></label><label>Élève<select value={student} onChange={e=>setStudent(e.target.value)}><option value="">Sélectionner</option>{students.map(s=><option key={s.id} value={s.id}>{s.last_name} {s.first_name}</option>)}</select></label><button disabled={disabled||!scale||!student} onClick={()=>onAssign(scale,student)}>Attribuer le frais</button></div></>}
function SettingsForm({initial,disabled,onSave}:{initial:Loaded["settings"];disabled:boolean;onSave:(v:{receipt_prefix:string;parent_publication_enabled:boolean;receipt_footer:string|null;financial_contact:string|null;print_format:"a4"|"thermal_80"})=>void}){const[prefix,setPrefix]=useState(initial?.receipt_prefix||"REC");const[publish,setPublish]=useState(initial?.parent_publication_enabled||false);const[footer,setFooter]=useState(initial?.receipt_footer||"");const[format,setFormat]=useState<"a4"|"thermal_80">(initial?.print_format||"a4");return <div className={styles.form}><label>Préfixe<input value={prefix} onChange={e=>setPrefix(e.target.value.toUpperCase())}/></label><label>Format<select value={format} onChange={e=>setFormat(e.target.value as "a4"|"thermal_80")}><option value="a4">A4</option><option value="thermal_80">Thermique 80 mm</option></select></label><label className={styles.check}><input type="checkbox" checked={publish} onChange={e=>setPublish(e.target.checked)}/>Publier dans l’espace parent</label><label>Texte de pied<textarea value={footer} onChange={e=>setFooter(e.target.value)}/></label><button disabled={disabled} onClick={()=>onSave({receipt_prefix:prefix,parent_publication_enabled:publish,receipt_footer:footer||null,financial_contact:null,print_format:format})}>Enregistrer</button></div>}
function Operations({payments,onCancel}:{payments:PaymentRow[];onCancel?:(p:PaymentRow)=>void}){return <div className={styles.panel}><h2>Dernières opérations</h2><table><thead><tr><th>Reçu</th><th>Payeur</th><th>Date</th><th>Montant</th><th>État</th><th></th></tr></thead><tbody>{payments.slice(0,12).map(p=><tr key={p.id}><td>{p.receipt_number}</td><td>{p.payer_name}</td><td>{new Date(p.paid_at).toLocaleString("fr-FR")}</td><td>{formatFcfa(p.amount_fcfa)}</td><td>{p.status==="cancelled"?"ANNULÉ":p.status}</td><td>{onCancel&&p.status==="active"&&<button onClick={()=>onCancel(p)}>Annuler</button>}</td></tr>)}</tbody></table></div>}
function ReceiptView({payment,student}:{payment:PaymentRow;student?:Loaded["students"][number]}){return <article className={styles.receipt} id="finance-receipt"><header><FileText/><div><h2>Reçu {payment.receipt_number}</h2><p>{new Date(payment.paid_at).toLocaleString("fr-FR")}</p></div></header>{payment.status==="cancelled"&&<strong className={styles.cancelled}>ANNULÉ</strong>}<dl><dt>Élève</dt><dd>{student?`${student.last_name} ${student.first_name}`:"Élève"}</dd><dt>Payeur</dt><dd>{payment.payer_name}</dd><dt>Montant</dt><dd>{formatFcfa(payment.amount_fcfa)}</dd><dt>Moyen</dt><dd>{payment.payment_method}</dd><dt>Caissier</dt><dd>Utilisateur connecté</dd></dl><div className={styles.signature}>Signature / cachet</div><button className={styles.noPrint} onClick={()=>window.print()}><Printer/>Imprimer le reçu</button></article>}
