"use client";
import {useMemo,useState}from"react";
import {ArrowDown,ArrowUp,Plus,Trash2}from"lucide-react";
import {buildInstallments,formatFcfa,previewCollectiveAssignment,validateCustomInstallments,type CustomInstallmentInput}from"@/lib/finance/calculations";
import type{loadFinanceData}from"@/lib/finance/store";
import styles from"./FinanceManager.module.css";
type Data=Awaited<ReturnType<typeof loadFinanceData>>;
export function ScaleConfigurator({data,schoolId,disabled,onScale,onApply}:{data:Data;schoolId:string;disabled:boolean;onScale:(value:{feeTypeId:string;scopeType:string;gradeLevelId?:string;classGroupId?:string;studentId?:string;amountFcfa:number;publish:boolean;mode:string;installments:ReturnType<typeof buildInstallments>})=>void;onApply:(scaleId:string)=>void}){
 const[fee,setFee]=useState("");const[scope,setScope]=useState<"school"|"level"|"class"|"student">("school");const[target,setTarget]=useState("");const[amount,setAmount]=useState("");const[due,setDue]=useState("");const[mode,setMode]=useState<"single"|"monthly"|"quarterly"|"custom">("single");const[count,setCount]=useState("1");const[publish,setPublish]=useState(false);const[rows,setRows]=useState<CustomInstallmentInput[]>([{label:"Échéance 1",due_on:"",amount_fcfa:0,position:1}]);const[applyId,setApplyId]=useState("");const[filter,setFilter]=useState("");const[error,setError]=useState("");
 const levels=useMemo(()=>Array.from(new Map(data.classes.map(c=>[c.grade_level_id,c.grade_levels])).entries()).filter((x):x is [string,NonNullable<Data["classes"][number]["grade_levels"]>]=>Boolean(x[1])),[data.classes]);
 const students=data.students.filter(s=>`${s.last_name} ${s.first_name} ${s.registration_number||""}`.toLowerCase().includes(filter.toLowerCase()));
 const chosen=data.scales.find(s=>s.id===applyId);const preview=chosen?previewCollectiveAssignment(data.students.map(s=>{const c=data.classes.find(x=>x.id===s.class_group_id);return{id:s.id,active:true,schoolId,gradeLevelId:c?.grade_level_id||"",classGroupId:s.class_group_id||""}}),{id:chosen.id,scopeType:chosen.scope_type,schoolId,gradeLevelId:chosen.grade_level_id,classGroupId:chosen.class_group_id,studentId:chosen.student_id,amountFcfa:chosen.amount_fcfa},data.scales.filter(s=>s.fee_type_id===chosen.fee_type_id).map(s=>({id:s.id,scopeType:s.scope_type,gradeLevelId:s.grade_level_id,classGroupId:s.class_group_id,studentId:s.student_id})),data.charges.filter(c=>c.fee_type_id===chosen.fee_type_id).map(c=>({studentId:c.student_id,sourceScaleId:c.source_scale_id}))):null;
 function save(){try{setError("");const total=Number(amount);const installments=mode==="custom"?validateCustomInstallments(total,rows):buildInstallments(total,due,mode,Number(count));onScale({feeTypeId:fee,scopeType:scope,gradeLevelId:scope==="level"?target:undefined,classGroupId:scope==="class"?target:undefined,studentId:scope==="student"?target:undefined,amountFcfa:total,publish,mode,installments});}catch(e){setError(e instanceof Error?e.message:"Échéancier invalide.");}}
 function patchRow(index:number,part:Partial<CustomInstallmentInput>){setRows(current=>current.map((row,i)=>i===index?{...row,...part}:row));}function move(index:number,delta:number){setRows(current=>{const next=[...current];const targetIndex=index+delta;if(targetIndex<0||targetIndex>=next.length)return current;[next[index],next[targetIndex]]=[next[targetIndex],next[index]];return next.map((row,i)=>({...row,position:i+1}));});}
 const difference=Number(amount||0)-rows.reduce((sum,row)=>sum+Number(row.amount_fcfa||0),0);
 return <section><h3>Créer un barème et son échéancier</h3><div className={styles.form}><label>Type<select value={fee} onChange={e=>setFee(e.target.value)}><option value="">Sélectionner</option>{data.fees.map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></label><label>Périmètre<select value={scope} onChange={e=>{setScope(e.target.value as typeof scope);setTarget("")}}><option value="school">Tout l’établissement</option><option value="level">Un niveau</option><option value="class">Une classe</option><option value="student">Un élève</option></select></label>{scope==="level"&&<label>Niveau<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Sélectionner</option>{levels.map(([id,l])=><option key={id} value={id}>{l.name}</option>)}</select></label>}{scope==="class"&&<label>Classe<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Sélectionner</option>{data.classes.map(c=><option key={c.id} value={c.id}>{c.grade_levels?.name} — {c.name}</option>)}</select></label>}{scope==="student"&&<><label>Recherche<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Nom ou matricule"/></label><label>Élève<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Sélectionner</option>{students.map(s=><option key={s.id} value={s.id}>{s.last_name} {s.first_name} — {data.classes.find(c=>c.id===s.class_group_id)?.name||"sans classe"}</option>)}</select></label></>}<label>Montant FCFA<input type="number" min="1" step="1" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Mode<select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="single">Unique</option><option value="monthly">Mensuel</option><option value="quarterly">Trimestriel</option><option value="custom">Personnalisé</option></select></label>{mode!=="custom"&&<><label>Première date<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label>Nombre<input type="number" min="1" max="24" disabled={mode==="single"} value={count} onChange={e=>setCount(e.target.value)}/></label></>}<label className={styles.check}><input type="checkbox" checked={publish} onChange={e=>setPublish(e.target.checked)}/>Visible des parents</label></div>
 {mode==="custom"&&<div><h4>Échéances personnalisées</h4>{rows.map((row,index)=><div className={styles.scheduleRow} key={index}><b>{index+1}</b><input aria-label="Libellé" value={row.label} onChange={e=>patchRow(index,{label:e.target.value})}/><input aria-label="Date" type="date" value={row.due_on} onChange={e=>patchRow(index,{due_on:e.target.value})}/><input aria-label="Montant" type="number" min="1" step="1" value={String(row.amount_fcfa)} onChange={e=>patchRow(index,{amount_fcfa:Number(e.target.value)})}/><button aria-label="Monter" onClick={()=>move(index,-1)}><ArrowUp/></button><button aria-label="Descendre" onClick={()=>move(index,1)}><ArrowDown/></button><button aria-label="Supprimer" onClick={()=>setRows(current=>current.filter((_,i)=>i!==index).map((r,i)=>({...r,position:i+1})))}><Trash2/></button></div>)}<button onClick={()=>setRows(current=>[...current,{label:`Échéance ${current.length+1}`,due_on:"",amount_fcfa:0,position:current.length+1}])}><Plus/>Ajouter</button><p>Total saisi : {formatFcfa(Number(amount)-difference)} · Différence : {formatFcfa(Math.abs(difference))} {difference<0?"en trop":"manquants"}</p></div>}{error&&<p className={styles.error}>{error}</p>}<button disabled={disabled||!fee||Number(amount)<=0||(scope!=="school"&&!target)} onClick={save}>Enregistrer le barème</button>
 <hr/><h3>Appliquer collectivement</h3><label>Barème<select value={applyId} onChange={e=>setApplyId(e.target.value)}><option value="">Sélectionner</option>{data.scales.map(s=><option key={s.id} value={s.id}>{data.fees.find(f=>f.id===s.fee_type_id)?.label} — {s.scope_type} — {formatFcfa(s.amount_fcfa)}</option>)}</select></label>{preview&&<div className={styles.preview}><p><b>Périmètre :</b> {chosen?.scope_type}</p><p><b>Élèves concernés :</b> {preview.eligibleIds.length}</p><p><b>Barème gagnant :</b> {preview.winningIds.length}</p><p><b>Couverts par un barème plus précis :</b> {preview.overshadowedIds.length}</p><p><b>Montant par élève :</b> {formatFcfa(preview.amountPerStudent)}</p><p><b>Total théorique :</b> {formatFcfa(preview.theoreticalTotal)}</p><p><b>Déjà facturés correctement :</b> {preview.alreadyAssignedIds.length}</p><p><b>Conflits à examiner :</b> {preview.conflictIds.length}</p><p><b>Nouvelles attributions :</b> {preview.pendingIds.length} ({formatFcfa(preview.newTotal)})</p>{preview.conflictIds.length>0&&<p className={styles.error}>Ces charges proviennent d’un autre barème et ne seront jamais remplacées automatiquement, notamment si elles ont déjà reçu un paiement.</p>}<button disabled={disabled||!preview.pendingIds.length} onClick={()=>confirm(`Appliquer ce barème à ${preview.pendingIds.length} élève(s) ?`)&&onApply(applyId)}>Confirmer l’attribution</button></div>}</section>;
}
