import{readFileSync}from"node:fs";import{resolve}from"node:path";import{describe,expect,it}from"vitest";
const read=(file:string)=>readFileSync(resolve(process.cwd(),file),"utf8");
const manager=read("components/finance/FinanceManager.tsx"),configurator=read("components/finance/ScaleConfigurator.tsx"),store=read("lib/finance/store.ts"),migration=read("supabase/migrations/100_finance_scolarite.sql");
describe("parcours financier réellement câblé",()=>{
 it("relie type, barème, collectif, encaissement, annulation et clôture",()=>{for(const fn of ["saveFeeType","configureScale","applyScaleCollectively","recordPayment","cancelPayment","closeCash"])expect(manager).toContain(fn);for(const rpc of ["configure_finance_scale","apply_finance_scale_collectively","record_finance_payment","cancel_finance_payment","close_finance_cash"])expect(store).toContain(rpc);for(const sqlfn of ["configure_finance_scale","apply_finance_scale_collectively","record_finance_payment","cancel_finance_payment","close_finance_cash"])expect(migration).toContain(`function public.${sqlfn}`);});
 it("expose les quatre périmètres et le personnalisé",()=>{for(const scope of ["school","level","class","student"])expect(configurator).toContain(`value=\"${scope}\"`);expect(configurator).toContain("validateCustomInstallments");expect(configurator).toContain("Ajouter");expect(configurator).toContain("Supprimer");});
 it("affiche la prévisualisation collective complète",()=>{for(const label of ["Élèves admissibles","Dossiers scolaires incomplets exclus","Montant par élève","Total théorique","Déjà facturés","Nouvelles attributions"])expect(configurator).toContain(label);});
 it("affiche les barèmes supplantés et les conflits sans remplacement silencieux",()=>{for(const label of ["Barème gagnant","Couverts par un barème plus précis","Conflits à examiner","ne seront jamais remplacées automatiquement"])expect(configurator).toContain(label);expect(manager).toContain("conflict_count");expect(manager).toContain("overshadowed_count");});
 it("relie échéances, paiements partiels, reçu, impayés et familles",()=>{expect(manager).toContain("selectedInstallments");expect(manager).toContain("setAmount");expect(manager).toContain("FinanceReceipt");expect(manager).toContain("Élèves et impayés");expect(manager).toContain("Situation des familles");});
});
