import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { resolve } from "node:path";
import { buildReceiptPrintHtml, computeReceiptBalances, paymentMethodLabel } from "@/components/finance/FinanceReceipt";
import type { ChargeInstallmentRow, ChargeRow, PaymentRow } from "@/lib/finance/store";

const root=process.cwd();
const component=readFileSync(resolve(root,"components/finance/FinanceReceipt.tsx"),"utf8");
const manager=readFileSync(resolve(root,"components/finance/FinanceManager.tsx"),"utf8");
const css=readFileSync(resolve(root,"components/finance/FinanceManager.module.css"),"utf8");
const store=readFileSync(resolve(root,"lib/finance/store.ts"),"utf8");

const payment=(overrides:Partial<PaymentRow>={}):PaymentRow=>({id:"payment-1",student_id:"student-1",payer_name:"Parent Exemple",amount_fcfa:6000,paid_at:"2026-08-28T09:30:00Z",payment_method:"cash",receipt_number:"REC-2026-000001",status:"active",cancellation_reason:null,cancelled_at:null,cancelled_by:null,collected_by:"cashier-1",cashier:{first_name:"Aline",last_name:"Moussavou"},...overrides});
const charge:ChargeRow={id:"charge-1",student_id:"student-1",fee_type_id:"fee-1",source_scale_id:"scale-1",amount_fcfa:30000,status:"active",finance_fee_types:{label:"Scolarité"}};
const installment:ChargeInstallmentRow={id:"installment-1",charge_id:"charge-1",label:"Échéance 1",due_on:"2026-09-05",amount_fcfa:10000,status:"active"};

describe("impression professionnelle du reçu financier",()=>{
  it("construit un document HTML complet, isolé et contenant le reçu",()=>{const base={payment:payment(),school:{name:"École Test",logoUrl:"/logo.png",address:"Libreville"},academicYearLabel:"2026-2027",studentName:"DOE Ada",className:"CM2",feeLabel:"Scolarité",installmentLabel:"Échéance 1",installmentRemaining:4000,studentRemaining:24000,cashierName:"Aline Moussavou",footer:"Merci",format:"a4"} as Parameters<typeof buildReceiptPrintHtml>[0];const html=buildReceiptPrintHtml(base,"https://ecole.test/finance");const text=html.replace(/\s/g,"");expect(html).toContain("<!doctype html>");for(const value of ["REC-2026-000001","École Test","DOE Ada","Espèces","https://ecole.test/logo.png","Imprimer ou enregistrer en PDF"])expect(html).toContain(value);for(const amount of ["6000FCFA","4000FCFA","24000FCFA"])expect(text).toContain(amount);expect(html).toContain("size:A4 portrait");expect(html).toContain("margin:12mm");expect(html).toContain(".printActions{display:none!important}");expect(html).not.toMatch(/\.receipt\s*\{[^}]*display\s*:\s*none/);expect(buildReceiptPrintHtml({...base,format:"thermal_80"},"https://ecole.test")).toContain("size:80mm auto");});
  it("ouvre immédiatement une fenêtre autonome, attend le document, les ressources et deux rendus, puis imprime",()=>{expect(component).toContain('window.open("","_blank"');expect(component).toContain("La fenêtre d’impression a été bloquée");expect(component).not.toContain('document.createElement("iframe")');expect(component).not.toContain('width:"1px"');expect(component).not.toContain('height:"1px"');expect(component).toContain('doc.readyState!=="complete"');expect(component).toContain("await doc.fonts?.ready");expect(component).toContain("Array.from(doc.images)");expect(component).toContain("target.requestAnimationFrame(()=>target.requestAnimationFrame");expect(component.indexOf("await waitForDocumentLayout(doc,target)")).toBeLessThan(component.indexOf("target.print()"));});
  it("laisse la page du reçu ouverte et n’imprime qu’après le clic dans cette page",()=>{expect(component).toContain('getElementById("print-finance-receipt")');expect(component).toContain('printButton.addEventListener("click",()=>{target.focus();target.print()})');expect(component).not.toContain('addEventListener("afterprint"');expect(component).not.toContain("window.setTimeout(cleanup");expect((component.match(/target\.close\(\)/g)||[]).length).toBe(2);expect(component).toContain("if(printing.current)return");expect(component).toContain("finally{printing.current=false;setIsPrinting(false)}");});
  it("affiche une erreur compréhensible si la fenêtre est bloquée ou si l’impression échoue",()=>{expect(component).toContain("setPrintError(error instanceof Error?error.message");expect(component).toContain('role="alert"');expect(component).toContain("L’impression du reçu a échoué.");});
  it("ne dépend plus du portail ni de la classe temporaire body",()=>{expect(component).not.toContain("createPortal");expect(component).not.toContain("finance-receipt-printing");expect(css).not.toContain("body.finance-receipt-printing");});
  it("préserve les règles d’impression du récapitulatif de caisse",()=>{expect(css).toContain(".panel>*:not(.cashPrint)");expect(css).toContain(".cashPrint{display:block!important");});
  it("affiche les données disponibles sans inventer de coordonnées",()=>{for(const token of ["school.logoUrl","school.name","school.address","school.phone","school.email","academicYearLabel","studentName","className","feeLabel","installmentLabel","cashierName","data.footer"])expect(component).toContain(token);expect(component).not.toContain("Utilisateur connecté");});
  it("traduit cash en Espèces et conserve le vrai caissier",()=>{expect(paymentMethodLabel("cash")).toBe("Espèces");expect(payment().cashier).toEqual({first_name:"Aline",last_name:"Moussavou"});expect(manager).toContain('payment.cashier?.first_name');});
  it("calcule 4 000 FCFA sur l’échéance et 24 000 FCFA au total depuis les données serveur actives",()=>{const current=payment();const balances=computeReceiptBalances(current,[charge],[installment],[{payment_id:current.id,charge_installment_id:installment.id,amount_fcfa:6000}],[current],installment.id);expect(balances).toEqual({installmentRemaining:4000,studentRemaining:24000});const cancelled=payment({status:"cancelled"});expect(computeReceiptBalances(cancelled,[charge],[installment],[{payment_id:cancelled.id,charge_installment_id:installment.id,amount_fcfa:6000}],[cancelled],installment.id)).toEqual({installmentRemaining:10000,studentRemaining:30000});});
  it("recharge paiements, allocations et charges avant de construire le reçu",()=>{expect(store).toContain('from("finance_payment_allocations")');expect(store).toContain("finance_payments!inner(school_id,academic_year_id)");expect(manager).toContain("const fresh=await reload(context)");expect(manager).toContain("fresh?.payments.find");expect(manager).toContain("data.allocations");});
  it("conserve strictement les migrations 100 à 103",()=>{const hashes:Record<string,string>={"100_finance_scolarite.sql":"53d263abb73aa8a20e41197cb4e36c46679830221f490c4f1331a02711cf0c80","101_finance_internal_function_privileges.sql":"e707ca867ff9ed0b7db881bce2a11fd6bf75b777f25a35e80d618467ee5bf3cc","102_student_records_academic_year_integrity.sql":"22f1846efe10d1fa7b1b558c9230d59f4f5457e296a2d0d1663a1e68bdc3d470","103_finance_receipt_sequence_ambiguity.sql":"30a29731842c96f93863449c30004baf6d972bfd0acb2c30eaa0fd3080de9b56"};for(const[name,hash]of Object.entries(hashes)){const actual=createHash("sha256").update(readFileSync(resolve(root,"supabase/migrations",name))).digest("hex");expect(actual).toBe(hash);}});
});
