"use client";

import { createClient } from "@/lib/supabase/client";
import { resolveStorageStatus, withTimeout, type StorageMode } from "@/lib/storage-mode";

export type ProgramItem={id:string;subject:string;grade:string;week:number;competency:string;objective:string;topic:string;hours:number;note:string;official:boolean};
const examples:ProgramItem[]=[
 {id:"demo-fr-primaire-5-1",subject:"Français",grade:"5e Année",week:1,competency:"Mobiliser les ressources de la langue pour comprendre et produire un texte.",objective:"Identifier les informations essentielles d’un texte narratif.",topic:"Le récit bref et sa structure",hours:3,note:"Exemple pédagogique — à valider",official:false},
 {id:"demo-fr-primaire-5-2",subject:"Français",grade:"5e Année",week:2,competency:"Utiliser les outils de la langue en contexte.",objective:"Reconnaître et employer les expansions du nom.",topic:"Les expansions du nom",hours:3,note:"Exemple pédagogique — à valider",official:false},
 {id:"demo-math-primaire-5-1",subject:"Mathématiques",grade:"5e Année",week:1,competency:"Résoudre une situation mobilisant les nombres.",objective:"Lire, écrire et comparer les nombres décimaux.",topic:"Nombres décimaux",hours:4,note:"Exemple pédagogique — à valider",official:false},
];

export async function listPrograms():Promise<{items:ProgramItem[];mode:StorageMode;message:string}>{const status=await resolveStorageStatus();if(status.mode!=="cloud")return{items:examples,mode:status.mode,message:"Contenu officiel en cours d’intégration"};try{const{data,error}=await withTimeout(createClient().from("weekly_progressions").select("id,week_number,suggested_topic,suggested_hours,notes,curricula!inner(status,subjects(name),grade_levels(code,name)),learning_objectives(title,competencies(title))").order("week_number"));if(error)throw error;const remote=(data||[]).map((row:Record<string,unknown>)=>{const curriculum=row.curricula as {status?:string;subjects?:{name?:string};grade_levels?:{code?:string;name?:string}};const objective=row.learning_objectives as {title?:string;competencies?:{title?:string}}|null;return{id:String(row.id),subject:curriculum.subjects?.name||"Matière",grade:curriculum.grade_levels?.code||curriculum.grade_levels?.name||"Niveau",week:Number(row.week_number),competency:objective?.competencies?.title||"Compétence à renseigner",objective:objective?.title||"Objectif à renseigner",topic:String(row.suggested_topic||"Notion à renseigner"),hours:Number(row.suggested_hours||0),note:String(row.notes||""),official:curriculum.status==="published"};});return{items:remote.length?remote:examples,mode:"cloud",message:remote.length?"Progressions chargées depuis Supabase":"Contenu officiel en cours d’intégration"};}catch{return{items:examples,mode:"offline",message:"Service indisponible : exemples pédagogiques affichés"};}}
