import { matchesRoutePath } from "@/lib/auth/path-matching";

export const PROTECTED_PREFIXES = [
  "/gabon-educ/tableau-de-bord",
  "/gabon-educ/mes-fiches",
  "/gabon-educ/cahier-de-textes",
  "/gabon-educ/mes-classes",
  "/gabon-educ/preparer-un-cours",
  "/gabon-educ/generateur-ia",
  "/gabon-educ/programmes-apc",
  "/gabon-educ/evaluations",
  "/gabon-educ/notes",
  "/gabon-educ/bulletins",
  "/gabon-educ/parametres",
  "/gabon-educ/modules",
  "/gabon-educ/administration",
  "/gabon-educ/secretariat",
  "/gabon-educ/etablissement",
  "/gabon-educ/utilisateurs",
  "/gabon-educ/personnel",
  "/gabon-educ/creer-enseignant",
  "/gabon-educ/eleves",
  "/gabon-educ/parents",
  "/gabon-educ/inscription",
  "/gabon-educ/inscriptions",
  "/gabon-educ/classes",
  "/gabon-educ/matieres",
  "/gabon-educ/emplois-du-temps",
  "/gabon-educ/annonces",
  "/gabon-educ/communication",
  "/gabon-educ/documents",
  "/gabon-educ/notes-bulletins",
  "/gabon-educ/modele-bulletin",
  "/gabon-educ/saisie-bulletin",
  "/gabon-educ/impression-bulletins",
  "/gabon-educ/bulletins-publication",
  "/gabon-educ/journal-audit",
  "/gabon-educ/import-export",
  "/gabon-educ/synchronisation",
  "/gabon-educ/diagnostic",
  "/gabon-educ/modules-a-venir",
  "/gabon-educ/abonnement",
  "/gabon-educ/service-abonnements",
  "/gabon-educ-service",
  "/gabon-educ/notifications",
  "/gabon-educ/assiduite",
  "/gabon-educ/espace-parent",
  "/gabon-educ/espace-eleve",
] as const;

export function isProtectedPath(pathname: string): boolean {
  return PROTECTED_PREFIXES.some((prefix) => matchesRoutePath(pathname, prefix));
}
